apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 5m
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      version: "19.0.1"  # Replace with the desired chart version
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
      interval: 5m
  values:
    alertmanager:
      enabled: true
    server:
      persistentVolume:
        enabled: true

